# Generated by Django 5.2.1 on 2025-06-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='client',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='manager',
        ),
    ]
