# Generated by Django 5.2.1 on 2025-06-03 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_deal_client_remove_deal_manager'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal'),
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
