# Generated by Django 5.2.1 on 2025-06-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_comment_task_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
